# Generated by Django 4.2.16 on 2026-06-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEOReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shock_type', models.CharField(max_length=50)),
                ('severity', models.IntegerField()),
                ('report_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CountryRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('risk_score', models.IntegerField(help_text='0-100 risk score')),
                ('oil_exposure', models.FloatField(default=0)),
                ('semiconductor_exposure', models.FloatField(default=0)),
                ('rare_earth_exposure', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Country risks',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='ShockSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shock_type', models.CharField(max_length=50)),
                ('severity', models.IntegerField()),
                ('price_increase_pct', models.FloatField()),
                ('shortage_probability', models.FloatField()),
                ('affected_countries', models.IntegerField()),
                ('gdp_impact_pct', models.FloatField()),
                ('results_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('oil', 'Oil'), ('semiconductor', 'Semiconductor'), ('rare_earth', 'Rare Earth')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_price_impact', models.FloatField(help_text='Base price increase % at severity 50')),
                ('base_shortage_prob', models.FloatField(help_text='Base shortage probability % at severity 50')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('shock_type', models.CharField(max_length=50)),
                ('recommendation', models.CharField(choices=[('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell')], max_length=10)),
                ('confidence', models.IntegerField(help_text='Confidence score 0-100')),
                ('expected_return', models.FloatField(help_text='Expected 12-month return %')),
                ('rationale', models.TextField()),
            ],
            options={
                'ordering': ['sector'],
                'unique_together': {('sector', 'shock_type')},
            },
        ),
    ]
